# Start from golang v1.11 base image
FROM golang:1.12

# Add Maintainer Info
LABEL maintainer="Sven <sven@testthedocs.org>"

# Go get boilr
RUN go get github.com/Ilyes512/boilr

# Run the executable
CMD ["boilr"]

