# This goes in a file named either `.vale.ini` or `_vale.ini`.

StylesPath = .ci/vale/styles
MinAlertLevel = suggestion # suggestion, warning or error

# Only Markdown and .txt files; change to whatever you're using.
[*.{md,rst}]
# List of styles to load.
# The line below loads ALL styles from the configured dirs and overwrites.
# the setup under styles (below).
BasedOnStyles = proselint, pronoxiv
# Styles
# The lines below ONLY loads the configured checks.
proselint.But = suggestion
proselint.Very = suggestion
proselint.Simple = suggestion
proselint.GenderBias = suggestion
pronovix.E-Prime = suggestion
pronovix.Anthropomorphism = suggestion
pronovix.ThereIs = suggestion
pronoxiv.Spacing = suggestion
pronovix.OxfordComma = suggestion
pronovix.Hedging = suggestion
pronovix.Titles = suggestion
pronovix.ListStart = suggestion
pronovix.Quotes = suggestion
pronovix.SentenceLength = suggestion
pronovix.Passive = suggestion
pronovix.Repetition = suggestion
pronovix.Spelling = suggestion
pronovix.Link = suggestion
pronovix.Testme = error
